<a href="https://colab.research.google.com/github/murodd02/Datas1/blob/main/Mantiqiy_shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

In [22]:

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [24]:
cond = np.array
cond

<function numpy.array>

In [25]:
result = np.where(cond,xarr,yarr)
result

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [27]:
arr=np.random.randn(4,4)
arr

array([[ 0.76336809, -0.31423778, -0.95431311, -0.29390969],
       [ 0.09958356,  1.00228564,  0.46338916, -1.06518075],
       [ 0.38082077, -1.27437899, -1.45464617,  1.66712811],
       [ 0.05691003,  0.20882657, -0.29060361, -0.62549943]])

In [28]:
results = np.where(arr<0, -2, 2)
results

array([[ 2, -2, -2, -2],
       [ 2,  2,  2, -2],
       [ 2, -2, -2,  2],
       [ 2,  2, -2, -2]])