<a href="https://colab.research.google.com/github/murodd02/Datas1/blob/main/Matematik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

In [30]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(10,22).reshape(3,4)

In [31]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [38]:
arr2-arr1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [42]:
arr2**2

array([[100, 121, 144, 169],
       [196, 225, 256, 289],
       [324, 361, 400, 441]])