<a href="https://colab.research.google.com/github/murodd02/Datas1/blob/main/Matematik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

In [45]:
arr = np.random.randn(6,5)
arr

array([[ 0.72210634,  3.0741604 ,  0.38505818,  1.17307561,  0.13890103],
       [-0.85405972,  0.40141703,  0.73258419,  1.03841388, -1.09677516],
       [-0.09747939, -0.29601554, -0.63092586,  0.49780899,  1.09188562],
       [ 1.64314064,  0.40090428,  0.51970874,  0.33049507, -0.38737137],
       [ 0.40136336, -0.08388575, -0.30150263,  1.38531547,  2.58278354],
       [-1.61405692, -0.20451658, -0.77981832, -0.01371355, -1.78373027]])

In [46]:
arr.sum()

8.375271309500809

In [47]:
data = np.arange(7)
data

array([0, 1, 2, 3, 4, 5, 6])

In [48]:
mean = np.sum(data)/len(data)
mean

3.0

In [49]:
data.mean()

3.0

In [50]:
arr

array([[ 0.72210634,  3.0741604 ,  0.38505818,  1.17307561,  0.13890103],
       [-0.85405972,  0.40141703,  0.73258419,  1.03841388, -1.09677516],
       [-0.09747939, -0.29601554, -0.63092586,  0.49780899,  1.09188562],
       [ 1.64314064,  0.40090428,  0.51970874,  0.33049507, -0.38737137],
       [ 0.40136336, -0.08388575, -0.30150263,  1.38531547,  2.58278354],
       [-1.61405692, -0.20451658, -0.77981832, -0.01371355, -1.78373027]])

In [51]:
arr.mean()

0.27917571031669364

In [52]:
np.mean(arr, axis=1)

array([ 1.09866031,  0.04431604,  0.11305476,  0.50137547,  0.7968148 ,
       -0.87916713])

In [53]:
arr.mean(axis=0)

array([ 0.03350239,  0.54867731, -0.01248262,  0.73523258,  0.0909489 ])

In [54]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21])