<a href="https://colab.research.google.com/github/murodd02/Datas1/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np

In [56]:
arr = np.random.rand(5)
arr

array([0.97394635, 0.08613994, 0.62035382, 0.34755721, 0.96308068])

In [57]:
sorted_arr = np.sort(arr)
sorted_arr

array([0.08613994, 0.34755721, 0.62035382, 0.96308068, 0.97394635])

In [58]:
rev_arr = -np.sort(-arr)
rev_arr

array([0.97394635, 0.96308068, 0.62035382, 0.34755721, 0.08613994])

In [59]:
arr2d = np.random.randn(2,4)
arr2d

array([[-1.24604466,  1.28105032, -0.9911269 ,  0.02746488],
       [-0.36960622, -0.28605469,  0.74697978, -0.42911026]])

In [60]:
row_srt = np.sort(arr2d, axis=0)
row_srt

array([[-1.24604466, -0.28605469, -0.9911269 , -0.42911026],
       [-0.36960622,  1.28105032,  0.74697978,  0.02746488]])

In [61]:
cor_srt = np.sort(arr2d, axis=1)
cor_srt

array([[-1.24604466, -0.9911269 ,  0.02746488,  1.28105032],
       [-0.42911026, -0.36960622, -0.28605469,  0.74697978]])